global using Service.Abstraction.AdminService;
global using Service.Abstraction.PatientService;
global using Shared.PatientModels;
global using AutoMapper;
global using Domain.Contracts.IRepositories;
global using Domain.Entities;
global using Service.Abstraction;
global using Domain.Contracts.ISpecifications;
global using System.Linq.Expressions;
global using Service.Specifications.Patient;
global using Domain.Exceptions;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Tokens;
global using Service.Abstraction.AuthenticationService;
global using Shared;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Options;
global using Service.Abstraction.AuthenticationService;
global using Service.Abstraction.DoctorService;
global using Service.AuthenticationService;
global using Service.PatientService;
global using Shared.AuthenticationModels;
global using System;
global using System.Collections.Generic;
global using System.IdentityModel.Tokens.Jwt;
global using System.Linq;
global using System.Security.Claims;
global using System.Text;
global using System.Threading.Tasks;
global using Domain.Exceptions;
global using Domain.Exceptions.NotFoundExceptions;
global using Microsoft.Extensions.Configuration;
global using Shared.AppointmentModels;
global using Stripe;
global using Stripe.Climate;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Service.Abstraction.DoctorService;
global using Service.Specifications;
global using Service.Specifications.Doctor;
global using Shared.DoctorModels;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Domain.Entities;
global using Microsoft.AspNetCore.Identity;
global using Shared.AdminModels;

global using AppointmentType = Domain.Entities.AppointmentType;
global using Patient = Domain.Entities.Patient;
global using AppointmentStatus = Domain.Entities.AppointmentStatus;


